-- Class Activities 
SELECT * FROM PRODUCTS ;

SELECT * FROM PRODUCTS
WHERE PRODUCTID = 17 ;

SELECT * FROM PRODUCTS 
WHERE STOCKLEVEL BETWEEN 500 AND 1200 
ORDER BY PRICE ASC;

SELECT NAME AS 'PRODUCT NAME', S.QUANTITY AS 'AMOUNT SOLD'
FROM PRODUCTS AS P
INNER JOIN SALES AS S ON P.PRODUCTID = S.PRODUCTID;

SELECT * FROM PRODUCTS
LEFT JOIN SALES ON PRODUCTS.PRODUCTID = SALES.PRODUCTID; 

SELECT * FROM CATEGORIES 
JOIN products ON categories.CategoryID = products.CategoryID ;

SELECT NAME FROM CATEGORIES 
INNER JOIN products ON categories.Name = products.Name ;

SELECT NAME FROM PRODUCTS 
INNER JOIN SALES ON PRODUCTS.PRODUCTID = SALES.PRODUCTID
WHERE PRODUCTS.PRODUCTID = 1; 

-- Assingment
/* joins: select all the computers from the products table:
using the products table and the categories table, return the product name and the category name */
SELECT PRODUCTS.NAME, CATEGORIES.NAME
FROM PRODUCTS 
INNER JOIN CATEGORIES ON PRODUCTS.CATEGORYID = CATEGORIES.CATEGORYID
WHERE CATEGORIES.NAME = 'COMPUTERS';
 
/* joins: find all product names, product prices, and products ratings that have a rating of 5 */
SELECT PRODUCTS.NAME, PRODUCTS.PRICE, REVIEWS.RATING
FROM PRODUCTS
LEFT JOIN REVIEWS ON PRODUCTS.PRODUCTID = REVIEWS.PRODUCTID
WHERE REVIEWS.RATING = 5;
 
/* joins: find the employee with the most total quantity sold.  use the sum() function and group by */
SELECT EMPLOYEES.FIRSTNAME, EMPLOYEES.LASTNAME, SUM(SALES.QUANTITY) AS TOTAL 
FROM SALES 
INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEEID = SALES.EMPLOYEEID
GROUP BY EMPLOYEES.EMPLOYEEID
ORDER BY TOTAL DESC
LIMIT 1;
/* joins: find the name of the department, and the name of the category for Appliances and Games */
SELECT DEPARTMENTS.NAME , CATEGORIES.NAME 
FROM CATEGORIES 
JOIN DEPARTMENTS ON CATEGORIES.DEPARTMENTID = DEPARTMENTS.DEPARTMENTID
WHERE CATEGORIES.NAME  IN ('APPLIANCE', 'GAMES') ;

/* joins: find the product name, total # sold, and total price sold,
 for Eagles: Hotel California --You may need to use SUM() */
SELECT PRODUCTS.NAME, SUM(SALES.QUANTITY) AS TOTALQUANTITY, SUM(SALES.QUANTITY * SALES.PRICEPERUNIT) AS TOTALPRICE
FROM SALES
JOIN PRODUCTS ON SALES.PRODUCTID = PRODUCTS.PRODUCTID
WHERE PRODUCTS.NAME = 'EAGLES :HOTEL CALIFONIA'
GROUP BY PRODUCTS.NAME;

/* joins: find Product name, reviewer name, rating, and comment on the Visio TV. (only return for the lowest rating!) */
;

SELECT PRODUCTS.NAME, REVIEWS.REVIEWER, REVIEWS.RATING, REVIEWS.COMMENT
FROM REVIEWS
JOIN PRODUCTS ON REVIEWS.PRODUCTID = PRODUCTS.PRODUCTID
WHERE PRODUCTS.NAME = 'VISIO TV'
ORDER BY REVIEWS.RATING ASC
LIMIT 1;

-- ------------------------------------------ Extra - May be difficult
/* Your goal is to write a query that serves as an employee sales report.
This query should return:
-  the employeeID
-  the employee's first and last name
-  the name of each product
-  and how many of that product they sold */
SELECT EMPLOYEES.EMPLOYEEID, EMPLOYEES.FIRSTNAME, EMPLOYEES.LASTNAME, PRODUCTS.NAME, SUM(SALES.QUANTITY)
FROM EMPLOYEES
JOIN SALES ON EMPLOYEES.EMPLOYEEID = SALES.EMPLOYEEID
JOIN PRODUCTS ON SALES.PRODUCTID = PRODUCTS.PRODUCTID
GROUP BY  EMPLOYEES.EMPLOYEEID, EMPLOYEES.FIRSTNAME, EMPLOYEES.LASTNAME, PRODUCTS.NAME 
ORDER BY EMPLOYEES.EMPLOYEEID, PRODUCTS.NAME;



